swagger: "2.0"
info:
  title: апи сервиса
  description: Title
  version: 1.0.0
paths:
  /send:
    post:
      tags:
        - "sms"
      summary: "Отправить sms"
      description: "Ендпоинт для отправки sms"
      operationId: "sendSms"
      consumes:
        - "text/plain"
      parameters:
        - name: "body"
          in: "body"
          description: "Сообщение"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Отправка успешна"