spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
    active: native
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka